trigger:
  - main

pool: slave


variables:
  COMPONENT: 'payment'

resources:
  repositories:
    - repository: templates
      type: github
      name: GurukaYadav/roboshop-azure-devops-templates
      endpoint: GurukaYadav

stages:
  - template: python.yml@templates